### ISSUE TITLE
第三次作业反馈

### ISSUE THREAD

**Issue by iteratorlee** [Fyunnn/ichw#1]
前两题有更为简单的算法，供参考：
第一题：将所有的数进行异或，结果即为单着的数
第二题：将所有的数进行异或得到a，求1到100的异或得到b，a异或b即为重复的数

**Comment by Fyunnn** [comment]
收到！
二元逻辑运算均具有交换律**和结合律**，因此可以采用更简单的方法，下面是我对原理的理解：
1.由交换律：两个相同的数异或为0，所以这2n+1个数异或的最终结果与**n个0与那个单的数异或**结果相同，得到那个单的数
2.1到100异或为b，设重复的数为x，那么所有数异或的结果a=b xor x，那么x=a xor b，得到x
